name: Nightly

on:
  schedule:
    - cron: "0 6 * * 6"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: nightly

      - name: Install Ameba
        run: shards install

      - name: Check Format
        run: crystal tool format --check

      - name: Check Lints
        run: ./bin/ameba

      - name: Run Specs
        run: crystal spec
